# Generated by Django 6.0 on 2025-12-17 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportjob',
            name='output_file',
            field=models.FileField(blank=True, null=True, upload_to='exports/%Y/%m/%d/'),
        ),
    ]
