# Generated by Django 6.0 on 2025-12-18 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_subject_dataset_path'),
        ('generator', '0002_exportjob_output_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exportjob',
            name='subject_code',
        ),
        migrations.AddField(
            model_name='exportjob',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='export_jobs', to='accounts.subject'),
        ),
        migrations.AlterField(
            model_name='exportjob',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='FAILED', max_length=20),
        ),
    ]
