# Generated by Django 6.0 on 2025-12-18 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_subject_dataset_path'),
        ('generator', '0004_backfill_exportjob_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportjob',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='export_jobs', to='accounts.subject'),
        ),
    ]
